//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    sealed class Shoot_day_ : IAnimatedVisualSource
    {
        public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            if (!IsRuntimeCompatible())
            {
                return null;
            }
            return new AnimatedVisual(compositor);
        }

        static bool IsRuntimeCompatible()
        {
            if (!Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.Composition.CompositionGeometricClip"))
            {
                return false;
            }
            return true;
        }

        sealed class AnimatedVisual : IAnimatedVisual
        {
            const long c_durationTicks = 15830000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _colorBrush_AlmostGold_FFF8E60D;
            CompositionColorBrush _colorBrush_AlmostPeachPuff_FFFFC5AD;
            CompositionColorBrush _colorBrush_AlmostTomato_FFF0562E;
            CompositionColorBrush _colorBrush_Black;
            CompositionColorBrush _colorBrush_White;
            CubicBezierEasingFunction _cubicBezierEasingFunction_00;
            CubicBezierEasingFunction _cubicBezierEasingFunction_01;
            CubicBezierEasingFunction _cubicBezierEasingFunction_02;
            CubicBezierEasingFunction _cubicBezierEasingFunction_05;
            CubicBezierEasingFunction _cubicBezierEasingFunction_07;
            CubicBezierEasingFunction _cubicBezierEasingFunction_08;
            CubicBezierEasingFunction _cubicBezierEasingFunction_09;
            CompositionEllipseGeometry _ellipse_27p393;
            CompositionEllipseGeometry _ellipse_2p68;
            CompositionEllipseGeometry _ellipse_2p749;
            StepEasingFunction _holdThenStepEasingFunction;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            ContainerVisual _root;
            ScalarKeyFrameAnimation _rotationAngleInDegreesScalarAnimation_0_to_0_0;
            CompositionRoundedRectangleGeometry _roundedRectangle_26p434x29p715;
            ExpressionAnimation _scalarExpressionAnimation;
            StepEasingFunction _stepThenHoldEasingFunction;
            ScalarKeyFrameAnimation _tEndScalarAnimation_0_to_1_1;
            ScalarKeyFrameAnimation _tStartScalarAnimation_0_to_1_1;

            CompositionColorBrush ColorBrush_AlmostGold_FFF8E60D()
            {
                return _colorBrush_AlmostGold_FFF8E60D = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF8, 0xE6, 0x0D));
            }

            // Path 1
            CompositionColorBrush ColorBrush_AlmostOliveDrab_FF5D902C()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x5D, 0x90, 0x2C));
            }

            CompositionColorBrush ColorBrush_AlmostPeachPuff_FFFFC5AD()
            {
                return _colorBrush_AlmostPeachPuff_FFFFC5AD = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xC5, 0xAD));
            }

            // Layer (Shape): Shape Layer 7
            // Path 1
            CompositionColorBrush ColorBrush_AlmostSkyBlue_FF87DDF1()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x87, 0xDD, 0xF1));
            }

            // Path 1
            CompositionColorBrush ColorBrush_AlmostSteelBlue_FF587ED0()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x58, 0x7E, 0xD0));
            }

            // Layer (Shape): Shape Layer 7
            // Path 1
            CompositionColorBrush ColorBrush_AlmostTomato_FFEF562E()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEF, 0x56, 0x2E));
            }

            CompositionColorBrush ColorBrush_AlmostTomato_FFF0562E()
            {
                return _colorBrush_AlmostTomato_FFF0562E = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF0, 0x56, 0x2E));
            }

            CompositionColorBrush ColorBrush_Black()
            {
                return _colorBrush_Black = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00));
            }

            CompositionColorBrush ColorBrush_White()
            {
                return _colorBrush_White = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF));
            }

            // Layer (Shape): Shape Layer 7
            CompositionContainerShape ContainerShape_00()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(0, 0, 0, 0, 0, 0);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_01());
                shapes.Add(SpriteShape_02());
                shapes.Add(SpriteShape_03());
                result.StartAnimation("TransformMatrix._11", TransformMatrix_11ScalarAnimation_to_1());
                var controller = result.TryGetAnimationController("TransformMatrix._11");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.TransformMatrix._11";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TransformMatrix._22", _reusableExpressionAnimation);
                return result;
            }

            // Layer (Shape): Shape Layer 10
            CompositionContainerShape ContainerShape_01()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 226.632996F, 630.197021F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_02());
                return result;
            }

            // Transforms for Shape Layer 10
            CompositionContainerShape ContainerShape_02()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(165.410004F, -31.9169998F));
                result.CenterPoint = new Vector2(17.3929996F, -90.6070023F);
                result.RotationAngleInDegrees = -35;
                result.Scale = new Vector2(1.47000003F, 1.47000003F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_04());
                shapes.Add(SpriteShape_05());
                shapes.Add(SpriteShape_06());
                shapes.Add(SpriteShape_07());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 17.393),(my.Position.Y - (-90.607)))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_0());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Shape Layer 11
            CompositionContainerShape ContainerShape_03()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(-0.945518613F, 0.32556811F, -0.32556811F, -0.945518613F, 686.62439F, 347.885345F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_04());
                return result;
            }

            // Transforms for Shape Layer 11
            CompositionContainerShape ContainerShape_04()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(183.701004F, -44.9000015F));
                result.CenterPoint = new Vector2(17.3929996F, -90.6070023F);
                result.RotationAngleInDegrees = -133;
                result.Scale = new Vector2(1.47000003F, 1.47000003F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_08());
                shapes.Add(SpriteShape_09());
                shapes.Add(SpriteShape_10());
                shapes.Add(SpriteShape_11());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X - 17.393),(my.Position.Y - (-90.607)))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_1());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Shape Layer 4
            CompositionContainerShape ContainerShape_05()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(50, 50);
                result.Offset = new Vector2(346, 444);
                result.Scale = new Vector2(1.40999997F, 1.40999997F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_12());
                shapes.Add(SpriteShape_13());
                shapes.Add(SpriteShape_14());
                shapes.Add(SpriteShape_15());
                shapes.Add(SpriteShape_16());
                shapes.Add(SpriteShape_17());
                result.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_0());
                var controller = result.TryGetAnimationController("RotationAngleInDegrees");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Shape Layer 3
            CompositionContainerShape ContainerShape_06()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(50, 50);
                result.Offset = new Vector2(346, 444);
                result.Scale = new Vector2(1.40999997F, 1.40999997F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_07());
                result.StartAnimation("RotationAngleInDegrees", _rotationAngleInDegreesScalarAnimation_0_to_0_0);
                var controller = result.TryGetAnimationController("RotationAngleInDegrees");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms for Shape Layer 3
            CompositionContainerShape ContainerShape_07()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(-134, -59.9140015F);
                result.Offset = new Vector2(113.765999F, 65.0599976F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_18());
                shapes.Add(SpriteShape_19());
                shapes.Add(SpriteShape_20());
                shapes.Add(SpriteShape_21());
                shapes.Add(SpriteShape_22());
                result.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0_1());
                var controller = result.TryGetAnimationController("RotationAngleInDegrees");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Layer 1
            CompositionContainerShape ContainerShape_08()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 258, 155);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_09());
                return result;
            }

            // Transforms for Layer 1
            CompositionContainerShape ContainerShape_09()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(50, 161));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_23());
                result.StartAnimation("Scale", ScaleVector2Animation_0());
                var controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X),(my.Position.Y))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_2());
                controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Layer 2
            CompositionContainerShape ContainerShape_10()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 208, 346);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_11());
                return result;
            }

            // Transforms for Layer 2
            CompositionContainerShape ContainerShape_11()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(50, 50));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_24());
                result.StartAnimation("Scale", ScaleVector2Animation_1());
                var controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X),(my.Position.Y))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_3());
                controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): Layer 3
            CompositionContainerShape ContainerShape_12()
            {
                var result = _c.CreateContainerShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 295, 351);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_13());
                return result;
            }

            // Transforms for Layer 3
            CompositionContainerShape ContainerShape_13()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(50, 50));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_26());
                result.StartAnimation("Scale", ScaleVector2Animation_2());
                var controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Vector2((my.Position.X),(my.Position.Y))";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Position", PositionVector2Animation_4());
                controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_00()
            {
                return _cubicBezierEasingFunction_00 = _c.CreateCubicBezierEasingFunction(new Vector2(0.509000003F, 0), new Vector2(0.490999997F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_01()
            {
                return _cubicBezierEasingFunction_01 = _c.CreateCubicBezierEasingFunction(new Vector2(0.0579999983F, 0), new Vector2(0.185000002F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_02()
            {
                return _cubicBezierEasingFunction_02 = _c.CreateCubicBezierEasingFunction(new Vector2(0.814999998F, 0), new Vector2(0.941999972F, 1));
            }

            // RotationAngleInDegrees
            CubicBezierEasingFunction CubicBezierEasingFunction_03()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(0.300000012F, 0), new Vector2(0.699999988F, 1));
            }

            // RotationAngleInDegrees
            CubicBezierEasingFunction CubicBezierEasingFunction_04()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(0.300000012F, 0), new Vector2(0.153999999F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_05()
            {
                return _cubicBezierEasingFunction_05 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0), new Vector2(0.833000004F, 1));
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // RotationAngleInDegrees
            CubicBezierEasingFunction CubicBezierEasingFunction_06()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(1, 0), new Vector2(0, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_07()
            {
                return _cubicBezierEasingFunction_07 = _c.CreateCubicBezierEasingFunction(new Vector2(0.100000001F, 0), new Vector2(0.307000011F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_08()
            {
                return _cubicBezierEasingFunction_08 = _c.CreateCubicBezierEasingFunction(new Vector2(0.693000019F, 0), new Vector2(0.899999976F, 1));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_09()
            {
                return _cubicBezierEasingFunction_09 = _c.CreateCubicBezierEasingFunction(new Vector2(0.100000001F, 0), new Vector2(0.899999976F, 1));
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_27p393()
            {
                var result = _ellipse_27p393 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(27.3924999F, 27.3924999F);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_2p68()
            {
                var result = _ellipse_2p68 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(2.6795001F, 2.6795001F);
                return result;
            }

            // Ellipse Path 1.EllipseGeometry
            CompositionEllipseGeometry Ellipse_2p749()
            {
                var result = _ellipse_2p749 = _c.CreateEllipseGeometry();
                result.Radius = new Vector2(2.74900007F, 2.74900007F);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(396, -352));
                    builder.AddCubicBezier(new Vector2(336, -348), new Vector2(302, -292), new Vector2(302, -248));
                    builder.AddCubicBezier(new Vector2(302, -204), new Vector2(278, -138), new Vector2(192, -138));
                    builder.AddCubicBezier(new Vector2(106, -138), new Vector2(100, -30), new Vector2(100, -30));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(3.16000009F, -7.55000019F));
                    builder.AddLine(new Vector2(36.7550011F, -113.182999F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-47.7389984F, 9.60099983F));
                    builder.AddLine(new Vector2(-116.977997F, -66.086998F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-21.6930008F, 2.35500002F));
                    builder.AddLine(new Vector2(-65.6060028F, -149.029007F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(1.5F, -86.5F));
                    builder.AddCubicBezier(new Vector2(1.5F, -86.5F), new Vector2(3.25F, -75.25F), new Vector2(16.75F, -74.25F));
                    builder.AddCubicBezier(new Vector2(21.2649994F, -73.9160004F), new Vector2(31.75F, -77.75F), new Vector2(32.25F, -85));
                    builder.AddLine(new Vector2(1.5F, -86.5F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(23, -8.2840004F));
                    builder.AddCubicBezier(new Vector2(23, 4.41900015F), new Vector2(0.291000009F, 18.7919998F), new Vector2(0.291000009F, 18.7919998F));
                    builder.AddCubicBezier(new Vector2(0.291000009F, 18.7919998F), new Vector2(-23, 4.41900015F), new Vector2(-23, -8.2840004F));
                    builder.AddCubicBezier(new Vector2(-23, -20.9869995F), new Vector2(-3.20300007F, -22.5499992F), new Vector2(0.291000009F, -10.9040003F));
                    builder.AddCubicBezier(new Vector2(3.78500009F, -22.5499992F), new Vector2(23, -20.9869995F), new Vector2(23, -8.2840004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(100, -30));
                    builder.AddCubicBezier(new Vector2(100, -30), new Vector2(184.824997F, -75.2870026F), new Vector2(170, -160));
                    builder.AddCubicBezier(new Vector2(156, -240), new Vector2(264.802002F, -261.639008F), new Vector2(308, -270));
                    builder.AddCubicBezier(new Vector2(370, -282), new Vector2(398, -374), new Vector2(358, -420));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame  = true;
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                var propertySet = result.Properties;
                propertySet.InsertScalar("TStart", 0);
                propertySet.InsertScalar("TEnd", 0);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Min(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimStart", _reusableExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Max(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimEnd", _reusableExpressionAnimation);
                result.StartAnimation("TStart", TStartScalarAnimation_0_to_1_0());
                var controller = result.TryGetAnimationController("TStart");
                controller.Pause();
                controller.StartAnimation("Progress", ScalarExpressionAnimation());
                result.StartAnimation("TEnd", TEndScalarAnimation_0_to_1_0());
                controller = result.TryGetAnimationController("TEnd");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                var propertySet = result.Properties;
                propertySet.InsertScalar("TStart", 0);
                propertySet.InsertScalar("TEnd", 0);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Min(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimStart", _reusableExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Max(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimEnd", _reusableExpressionAnimation);
                result.StartAnimation("TStart", TStartScalarAnimation_0_to_1_1());
                var controller = result.TryGetAnimationController("TStart");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("TEnd", TEndScalarAnimation_0_to_1_1());
                controller = result.TryGetAnimationController("TEnd");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                var propertySet = result.Properties;
                propertySet.InsertScalar("TStart", 0);
                propertySet.InsertScalar("TEnd", 0);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Min(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimStart", _reusableExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Max(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimEnd", _reusableExpressionAnimation);
                result.StartAnimation("TStart", _tStartScalarAnimation_0_to_1_1);
                var controller = result.TryGetAnimationController("TStart");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("TEnd", _tEndScalarAnimation_0_to_1_1);
                controller = result.TryGetAnimationController("TEnd");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                var propertySet = result.Properties;
                propertySet.InsertScalar("TStart", 0);
                propertySet.InsertScalar("TEnd", 0);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Min(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimStart", _reusableExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Max(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimEnd", _reusableExpressionAnimation);
                result.StartAnimation("TStart", _tStartScalarAnimation_0_to_1_1);
                var controller = result.TryGetAnimationController("TStart");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("TEnd", _tEndScalarAnimation_0_to_1_1);
                controller = result.TryGetAnimationController("TEnd");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_4()
            {
                var result = _pathGeometry_4 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_5()
            {
                var result = _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_5()));
                return result;
            }

            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_6()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_6()));
                var propertySet = result.Properties;
                propertySet.InsertScalar("TStart", 0);
                propertySet.InsertScalar("TEnd", 0);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Min(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimStart", _reusableExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "Max(my.TStart, my.TEnd)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("TrimEnd", _reusableExpressionAnimation);
                result.StartAnimation("TStart", TStartScalarAnimation_0_to_1_2());
                var controller = result.TryGetAnimationController("TStart");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("TEnd", TEndScalarAnimation_0_to_1_2());
                controller = result.TryGetAnimationController("TEnd");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_0()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(165.410004F, -31.9169998F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.236842111F, new Vector2(5.79500008F, 81.3759995F), CubicBezierEasingFunction_01());
                result.InsertKeyFrame(0.447368413F, new Vector2(165.410004F, -31.9169998F), CubicBezierEasingFunction_02());
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_1()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(183.701004F, -44.9000015F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.552631557F, new Vector2(183.701004F, -44.9000015F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.789473712F, new Vector2(24.0869999F, 68.3929977F), _cubicBezierEasingFunction_01);
                result.InsertKeyFrame(1, new Vector2(183.701004F, -44.9000015F), _cubicBezierEasingFunction_02);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_2()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(50, 161), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.631578863F, "(Pow(1 - _.t0, 3) * Vector2(50,161)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(17,104)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(84,96)) + (Pow(_.t0, 3) * Vector2(50,50))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.631578982F, new Vector2(50, 50), _stepThenHoldEasingFunction);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_3()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(50, 50), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.184210524F, new Vector2(50, 50), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.736841977F, "(Pow(1 - _.t1, 3) * Vector2(50,50)) + (3 * Square(1 - _.t1) * _.t1 * Vector2(17,(-7))) + (3 * (1 - _.t1) * Square(_.t1) * Vector2(84,(-15))) + (Pow(_.t1, 3) * Vector2(50,(-61)))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.736842096F, new Vector2(50, -61), _stepThenHoldEasingFunction);
                return result;
            }

            // Position
            Vector2KeyFrameAnimation PositionVector2Animation_4()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(50, 50), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.394736856F, new Vector2(50, 50), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.947368324F, "(Pow(1 - _.t2, 3) * Vector2(50,50)) + (3 * Square(1 - _.t2) * _.t2 * Vector2(17,(-7))) + (3 * (1 - _.t2) * Square(_.t2) * Vector2(84,(-15))) + (Pow(_.t2, 3) * Vector2(50,(-61)))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.947368443F, new Vector2(50, -61), _stepThenHoldEasingFunction);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0);
                propertySet.InsertScalar("t0", 0);
                propertySet.InsertScalar("t1", 0);
                propertySet.InsertScalar("t2", 0);
                var children = result.Children;
                children.InsertAtTop(ShapeVisual());
                result.StartAnimation("t0", t0ScalarAnimation_to_1());
                var controller = result.TryGetAnimationController("t0");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("t1", t1ScalarAnimation_0_to_1());
                controller = result.TryGetAnimationController("t1");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("t2", t2ScalarAnimation_0_to_1());
                controller = result.TryGetAnimationController("t2");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_0()
            {
                var result = _rotationAngleInDegreesScalarAnimation_0_to_0_0 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.236842111F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.421052635F, -38, CubicBezierEasingFunction_03());
                result.InsertKeyFrame(0.605263174F, 10, CubicBezierEasingFunction_04());
                result.InsertKeyFrame(0.789473712F, 0, CubicBezierEasingFunction_05());
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.236842111F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.447368413F, -26, _cubicBezierEasingFunction_05);
                result.InsertKeyFrame(0.605263174F, 0, CubicBezierEasingFunction_06());
                return result;
            }

            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_26p434x29p715()
            {
                var result = _roundedRectangle_26p434x29p715 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(9.99999997E-07F, 9.99999997E-07F);
                result.Offset = new Vector2(-13.217F, -14.8575001F);
                result.Size = new Vector2(26.434F, 29.7150002F);
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_280p938x175p586()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(9.99999997E-07F, 9.99999997E-07F);
                result.Offset = new Vector2(-140.468994F, -87.7929993F);
                result.Size = new Vector2(280.937988F, 175.585999F);
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_280p938x34p586()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(9.99999997E-07F, 9.99999997E-07F);
                result.Offset = new Vector2(-140.468994F, -124.292999F);
                result.Size = new Vector2(280.937988F, 34.5859985F);
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            // Rectangle Path 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_282p293x31p566()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(9.99999997E-07F, 9.99999997E-07F);
                result.Offset = new Vector2(-141.1465F, -14.783F);
                result.Size = new Vector2(282.292999F, 31.566F);
                return result;
            }

            ExpressionAnimation ScalarExpressionAnimation()
            {
                var result = _scalarExpressionAnimation = _c.CreateExpressionAnimation();
                result.SetReferenceParameter("_", _root);
                result.Expression = "_.Progress";
                return result;
            }

            // Transforms: Layer 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(0, 0), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.368421048F, new Vector2(1, 1), CubicBezierEasingFunction_07());
                result.InsertKeyFrame(0.631578922F, new Vector2(0, 0), CubicBezierEasingFunction_08());
                return result;
            }

            // Transforms: Layer 2
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(0, 0), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.184210524F, new Vector2(0, 0), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.473684222F, new Vector2(1, 1), _cubicBezierEasingFunction_07);
                result.InsertKeyFrame(0.736842096F, new Vector2(0, 0), _cubicBezierEasingFunction_08);
                return result;
            }

            // Transforms: Layer 3
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_2()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(0, 0), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.394736856F, new Vector2(0, 0), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.684210539F, new Vector2(1, 1), _cubicBezierEasingFunction_07);
                result.InsertKeyFrame(0.947368443F, new Vector2(0, 0), _cubicBezierEasingFunction_08);
                return result;
            }

            ShapeVisual ShapeVisual()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1000, 1000);
                var shapes = result.Shapes;
                // Path 1
                shapes.Add(SpriteShape_00());
                // Layer (Shape): Shape Layer 7
                shapes.Add(ContainerShape_00());
                // Layer (Shape): Shape Layer 10
                shapes.Add(ContainerShape_01());
                // Layer (Shape): Shape Layer 11
                shapes.Add(ContainerShape_03());
                // Layer (Shape): Shape Layer 4
                shapes.Add(ContainerShape_05());
                // Layer (Shape): Shape Layer 3
                shapes.Add(ContainerShape_06());
                // Layer (Shape): Layer 1
                shapes.Add(ContainerShape_08());
                // Layer (Shape): Layer 2
                shapes.Add(ContainerShape_10());
                // Path 1
                shapes.Add(SpriteShape_25());
                // Layer (Shape): Layer 3
                shapes.Add(ContainerShape_12());
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 394, 848);
                result.Geometry = PathGeometry_0();
                result.StrokeBrush = ColorBrush_AlmostOliveDrab_FF5D902C();
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 25;
                return result;
            }

            // Layer (Shape): Shape Layer 7
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(-0.258819044F, 0.965925813F, -0.965925813F, -0.258819044F, 724, 512);
                result.Geometry = PathGeometry_1();
                result.StrokeBrush = ColorBrush_AlmostGold_FFF8E60D();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 11;
                return result;
            }

            // Layer (Shape): Shape Layer 7
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(-0.258819044F, 0.965925813F, -0.965925813F, -0.258819044F, 724, 512);
                result.Geometry = PathGeometry_2();
                result.StrokeBrush = ColorBrush_AlmostSkyBlue_FF87DDF1();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 11;
                return result;
            }

            // Layer (Shape): Shape Layer 7
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(-0.258819044F, 0.965925813F, -0.965925813F, -0.258819044F, 724, 512);
                result.Geometry = PathGeometry_3();
                result.StrokeBrush = ColorBrush_AlmostTomato_FFEF562E();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 11;
                return result;
            }

            // Transforms: Shape Layer 10
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 17.3929996F, -90.6070023F);
                result.FillBrush = _colorBrush_AlmostGold_FFF8E60D;
                result.Geometry = Ellipse_27p393();
                return result;
            }

            // Transforms: Shape Layer 10
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = ColorBrush_Black();
                result.Geometry = PathGeometry_4();
                return result;
            }

            // Transforms: Shape Layer 10
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 5.92999983F, -101.07F);
                result.FillBrush = _colorBrush_Black;
                result.Geometry = Ellipse_2p68();
                return result;
            }

            // Transforms: Shape Layer 10
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 27.7490005F, -100.500999F);
                result.FillBrush = _colorBrush_Black;
                result.Geometry = Ellipse_2p749();
                return result;
            }

            // Transforms: Shape Layer 11
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 17.3929996F, -90.6070023F);
                result.FillBrush = _colorBrush_AlmostGold_FFF8E60D;
                result.Geometry = _ellipse_27p393;
                return result;
            }

            // Transforms: Shape Layer 11
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _colorBrush_Black;
                result.Geometry = _pathGeometry_4;
                return result;
            }

            // Transforms: Shape Layer 11
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 5.92999983F, -101.07F);
                result.FillBrush = _colorBrush_Black;
                result.Geometry = _ellipse_2p68;
                return result;
            }

            // Transforms: Shape Layer 11
            // Ellipse Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 27.7490005F, -100.500999F);
                result.FillBrush = _colorBrush_Black;
                result.Geometry = _ellipse_2p749;
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_12()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 120.234001F, 94.8539963F);
                result.FillBrush = ColorBrush_White();
                result.Geometry = RoundedRectangle_280p938x175p586();
                result.StrokeBrush = ColorBrush_AlmostPeachPuff_FFFFC5AD();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 10;
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_13()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1.29385996F, 119.910995F, 22.843998F);
                result.FillBrush = _colorBrush_AlmostPeachPuff_FFFFC5AD;
                result.Geometry = RoundedRectangle_282p293x31p566();
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_14()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 32.2159958F, 22.8579979F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = RoundedRectangle_26p434x29p715();
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_15()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 90.2160034F, 22.8579979F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_16()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 149.216003F, 22.8579979F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 4
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_17()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 208.216003F, 22.8579979F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_18()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 6.46899986F, 29.7929993F);
                result.FillBrush = _colorBrush_AlmostPeachPuff_FFFFC5AD;
                result.Geometry = RoundedRectangle_280p938x34p586();
                result.StrokeBrush = _colorBrush_AlmostPeachPuff_FFFFC5AD;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 10;
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_19()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, -81.5490036F, -76.2030029F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_20()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, -23.5489998F, -76.2030029F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_21()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 35.4510002F, -76.2030029F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Layer (Shape): Shape Layer 3
            // Transforms: Shape Layer 3
            // Rectangle Path 1
            CompositionSpriteShape SpriteShape_22()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1.05999994F, 0, 0, 1.08000004F, 94.4509964F, -76.2030029F);
                result.FillBrush = _colorBrush_White;
                result.Geometry = _roundedRectangle_26p434x29p715;
                return result;
            }

            // Transforms: Layer 1
            // Path 1
            CompositionSpriteShape SpriteShape_23()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = ColorBrush_AlmostTomato_FFF0562E();
                result.Geometry = PathGeometry_5();
                return result;
            }

            // Transforms: Layer 2
            // Path 1
            CompositionSpriteShape SpriteShape_24()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _colorBrush_AlmostTomato_FFF0562E;
                result.Geometry = _pathGeometry_5;
                return result;
            }

            // Path 1
            CompositionSpriteShape SpriteShape_25()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(0.374606639F, -0.927183867F, 0.927183867F, 0.374606639F, 454.354858F, 889.956604F);
                result.Geometry = PathGeometry_6();
                result.StrokeBrush = ColorBrush_AlmostSteelBlue_FF587ED0();
                result.StrokeMiterLimit = 4;
                result.StrokeThickness = 25;
                return result;
            }

            // Transforms: Layer 3
            // Path 1
            CompositionSpriteShape SpriteShape_26()
            {
                var result = _c.CreateSpriteShape();
                result.FillBrush = _colorBrush_AlmostTomato_FFF0562E;
                result.Geometry = _pathGeometry_5;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame  = true;
                return result;
            }

            ScalarKeyFrameAnimation t0ScalarAnimation_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.631578863F, 1, CubicBezierEasingFunction_09());
                return result;
            }

            ScalarKeyFrameAnimation t1ScalarAnimation_0_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.184210628F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.736841977F, 1, _cubicBezierEasingFunction_09);
                return result;
            }

            ScalarKeyFrameAnimation t2ScalarAnimation_0_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.394736946F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.947368324F, 1, _cubicBezierEasingFunction_09);
                return result;
            }

            // TEnd
            ScalarKeyFrameAnimation TEndScalarAnimation_0_to_1_0()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.289473683F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.631578922F, 1, _cubicBezierEasingFunction_00);
                return result;
            }

            // TEnd
            ScalarKeyFrameAnimation TEndScalarAnimation_0_to_1_1()
            {
                var result = _tEndScalarAnimation_0_to_1_1 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.552631557F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.684210539F, 1, _cubicBezierEasingFunction_00);
                return result;
            }

            // TEnd
            ScalarKeyFrameAnimation TEndScalarAnimation_0_to_1_2()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.105263159F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.447368413F, 1, _cubicBezierEasingFunction_00);
                return result;
            }

            // Layer (Shape): Shape Layer 7
            ScalarKeyFrameAnimation TransformMatrix_11ScalarAnimation_to_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.368421048F, 1, _holdThenStepEasingFunction);
                return result;
            }

            // TStart
            ScalarKeyFrameAnimation TStartScalarAnimation_0_to_1_0()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.394736856F, 0, HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.815789461F, 1, CubicBezierEasingFunction_00());
                return result;
            }

            // TStart
            ScalarKeyFrameAnimation TStartScalarAnimation_0_to_1_1()
            {
                var result = _tStartScalarAnimation_0_to_1_1 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.578947365F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.736842096F, 1, _cubicBezierEasingFunction_00);
                return result;
            }

            // TStart
            ScalarKeyFrameAnimation TStartScalarAnimation_0_to_1_2()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.210526317F, 0, _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.631578922F, 1, _cubicBezierEasingFunction_00);
                return result;
            }

            internal AnimatedVisual(Compositor compositor)
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            Visual IAnimatedVisual.RootVisual => _root;
            TimeSpan IAnimatedVisual.Duration => TimeSpan.FromTicks(c_durationTicks);
            Vector2 IAnimatedVisual.Size => new Vector2(1000, 1000);
            void IDisposable.Dispose() => _root?.Dispose();
        }
    }
}
